name: video_alarm_app
description: A Flutter application for video alarms
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.6.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Video player dependencies
  video_player: ^2.7.2
  youtube_player_flutter: ^9.1.1
  
  # Audio/Alarm dependencies
  just_audio: ^0.9.34
  audio_service: ^0.18.10
  audio_session: ^0.1.16
  android_alarm_manager_plus: ^3.0.3
  
  # Storage
  shared_preferences: ^2.2.0
  
  # Other utilities
  path_provider: ^2.1.0
  intl: ^0.18.1
  provider: ^6.0.5

  file_picker: ^9.2.1
  chewie: ^1.11.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  # Add your assets and fonts configuration here if needed
  # assets:
  #   - assets/images/
  #   - assets/sounds/
  
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700